### ISSUE TITLE
Instant crash on startup

### ISSUE THREAD

**Issue by gcommit** [AkdM/KnightTouchBar2000#16]
Hi unfortunatly it crashes instantly when starting. I have the latest MacBook pro and the latest app release. Can you help?

<img width="425" alt="Bildschirmfoto 2019-09-20 um 11 27 59" src="https://user-images.githubusercontent.com/18714033/65316183-bd110800-db99-11e9-9bdb-72fbde2282cc.png">

**Comment by AkdM** [comment]
Please see: https://github.com/AkdM/KnightTouchBar2000/issues/15#issuecomment-525353956
