### ISSUE TITLE
Doesn't work in macOS Catalina

### ISSUE THREAD

**Issue by TheFound3r** [AkdM/KnightTouchBar2000#17]
Like a user earlier stated, this insta crashes and upon opening prompts a dialog:

"KnightTouchBar2000” will damage your computer. You should move it to the Trash."

I would really love to see an update to this program, its simply awesome.

**Comment by StefanPostma** [comment]
Same issue here

**Comment by AkdM** [comment]
#7, #9, #10, #11, #12, #13, #15, #16
