### ISSUE TITLE
It's crushed on MacOS 10.14.6 Mojave

### ISSUE THREAD

**Issue by LunaYJ** [AkdM/KnightTouchBar2000#19]
it's the detail:

Process:               KnightTouchBar2000 [18499]
Path:                  /Applications/KnightTouchBar2000.app/Contents/MacOS/KnightTouchBar2000
Identifier:            com.AnthonyDaMota.KnightTouchBar2000
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KnightTouchBar2000 [18499]
User ID:               502

Date/Time:             2019-12-03 11:32:41.665 +0800
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Bridge OS Version:     3.0 (14Y904)
Anonymous UUID:        EBC21F85-6D73-4BAD-62A1-7336D7DC626D

Sleep/Wake UUID:       C219E9AE-2E41-4A36-8ED4-327C68F92B3B

Time Awake Since Boot: 47000 seconds
Time Since Wake:       490 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010ab1c000-000000010ab24000 [   32K] r-x/rwx SM=COW  

Thread 0 Crashed:
0                                 	0x0000000115b01000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee50e3b38
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000115b01000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x10ab1c000 -        0x10ab23fff + (0) <247B3159-36C6-3833-83BC-D5621A8DBD8C> 
       0x115b00000 -        0x115b6a70f + (655.1.1) <DFC3C4AF-6F97-3B34-B18D-7DCB23F2A83A> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 63089
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=640K resident=0K(0%) swapped_out_or_unallocated=640K(100%)
Writable regions: Total=8400K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8400K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             240K        3 
__LINKEDIT                         180K        2 
__TEXT                             460K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             64.9M       11 

Model: MacBookPro14,3, BootROM 198.71.1.0.0, 4 processors, Intel Core i7, 2.8 GHz, 16 GB, SMC 2.45f0
Graphics: kHW_IntelHDGraphics630Item, Intel HD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro555Item, Radeon Pro 555, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x173), Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: USB2.0 Hub
USB Device: Varmilo Keyboard
USB Device: USB Billboard Device
USB Device: USB 2.0 BILLBOARD
USB Device: Apple T1 Controller
USB Device: USB3.0 Hub
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.1

**Comment by sifus** [comment]
+1
