### ISSUE TITLE
Release 1.1 does not start

### ISSUE THREAD

**Issue by boxmein** [AkdM/KnightTouchBar2000#7]
When I run release 1.1 by double-clicking the .app file, OSX tells me I should move it to the trash. When I run release 1.1 by right-clicking and selecting Open, I get this crash report:

```
Process:               KnightTouchBar2000 [83572]
Path:                  /Volumes/VOLUME/*/KnightTouchBar2000.app/Contents/MacOS/KnightTouchBar2000
Identifier:            com.AnthonyDaMota.KnightTouchBar2000
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KnightTouchBar2000 [83572]
User ID:               503

Date/Time:             2017-10-26 12:02:24.229 +0300
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        B2C52937-7170-76D6-6A1F-118EC0AF5AC1

Sleep/Wake UUID:       F26CFE90-858F-482A-893E-28C722EC9230

Time Awake Since Boot: 510000 seconds
Time Since Wake:       4600 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000100c9f000-0000000100ca7000 [   32K] r-x/rwx SM=COW   [w:5(]

Thread 0 Crashed:
0   ???                           	0x00000001033d0000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff5ef60ae8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00000001033d0000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x100c9f000 -        0x100ca6fff +??? (0) <9C9F24AF-E51B-344D-A06D-98215A9C4CAC> (null)
       0x1033cf000 -        0x10340cdc7 +??? (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 44895153
    thread_create: 0
    thread_set_state: 97

VM Region Summary:
ReadOnly portion of Libraries: Total=392K resident=0K(0%) swapped_out_or_unallocated=392K(100%)
Writable regions: Total=8400K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8400K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
__DATA                             232K        4 
__LINKEDIT                         112K        3 
__TEXT                             280K        3 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             64.6M       11 

Model: MacBookPro13,3, BootROM MBP133.0226.B25, 4 processors, Intel Core i7, 2,6 GHz, 16 GB, SMC 2.38f7
Graphics: Intel HD Graphics 530, Intel HD Graphics 530, Built-In
Graphics: Radeon Pro 450, AMD Radeon Pro 450, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x15A), Broadcom BCM43xx 1.0 (7.21.171.130.1a1)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: USB2.0 Hub
USB Device: USB-C Digital AV Multiport Adapter
USB Device: iBridge
USB Device: USB3.0 Hub
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.1
```

**Comment by omarpiani** [comment]
Do you have XCode?

**Comment by boxmein** [comment]
Yes :)

**Comment by JTSawyer** [comment]
I'm also experiencing this issue. Not sure if it's related to High Sierra or not...

**Comment by romeoro** [comment]
Can confirm on 2017 model @ 10.12.6

**Comment by ivanpk** [comment]
Confirm on 10.13.2 (17C88) 15" 2017 model

**Comment by AkdM** [comment]
Thanks for the report guys, I will work on this as soon as I get a new Macbook Pro (with Touchbar this time!).

**Comment by supradj** [comment]
`sudo spctl --master-disable` won't work

**Comment by athompso** [comment]
Even spctl --master-disable may not work, because of the specific error:
> spctl -a KnightTouchBar2000.app
> KnightTouchBar2000.app: CSSMERR_TP_CERT_REVOKED

Using codesign --extract-certificates to retrieve the developer certificate, I then further use
> ocsptool --ask http://ocsp.apple.com/ocsp-wwdr01 --load-issuer chain.pem --load-cert codesign0.pem

which reveals...
> [...]
> 		Certificate Status: revoked
>		Revocation time: Wed Sep 06 12:25:30 UTC 2017
> [...]

So, sorry, folks, AFAIK it's got nothing to do with what model of Macbook you're running or what OS, it's because the developer certificate Anthony used for this release build has been revoked.
Note that this isn't necessarily nefarious - there are several legitimate circumstances whereby Apple would revoke that cert and issue a new one, but in that case the release needs to be re-signed.

Building the app yourself, locally, and trying to run it should be much more successful... at least it won't run into this specific problem!

**Comment by AkdM** [comment]
I just released version 1.1.1.
Can you confirm it works now?

Thanks and sorry for the issue!

**Comment by 8938948** [comment]
@AkdM unfortunately still doesn't work for me

> Process:               KnightTouchBar2000 [1799]
> Path:                  /private/var/folders/*/KnightTouchBar2000.app/Contents/MacOS/KnightTouchBar2000
> Identifier:            com.AnthonyDaMota.KnightTouchBar2000
> Version:               ???
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           KnightTouchBar2000 [1799]
> User ID:               501
> 
> Date/Time:             2018-05-19 19:52:55.927 +0400
> OS Version:            Mac OS X 10.13.4 (17E199)
> Report Version:        12
> Bridge OS Version:     3.0 (14Y664)
> Anonymous UUID:        C04A4A46-9155-FD26-DB38-D9220F927B28
> 
> Sleep/Wake UUID:       010B69D6-2CA0-4544-AE20-B209193360FE
> 
> Time Awake Since Boot: 10000 seconds
> Time Since Wake:       4300 seconds
> 
> System Integrity Protection: enabled
> 
> Notes:                 Translocated Process
> 
> Crashed Thread:        0
> 
> Exception Type:        EXC_CRASH (Code Signature Invalid)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Reason:    Namespace CODESIGNING, Code 0x1
> 
> kernel messages:
> 
> VM Regions Near 0 (cr2):
> --> 
>     __TEXT                 0000000100852000-000000010085a000 [   32K] r-x/rwx SM=COW  P []
> 
> Thread 0 Crashed:
> 0   ???                           	0x00000001088c119c _dyld_start + 0
> 
> Thread 0 crashed with X86 Thread State (64-bit):
>   rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
>   rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeef3adad0
>    r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
>   r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
>   rip: 0x00000001088c119c  rfl: 0x0000000000000200  cr2: 0x0000000000000000
>   
> Logical CPU:     0
> Error Code:      0x00000000
> Trap Number:     0
> 
> 
> Binary Images:
>        0x100852000 -        0x100859fff +??? (0) <247B3159-36C6-3833-83BC-D5621A8DBD8C> (null)
>        0x1088c0000 -        0x10890a9df +??? (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> (null)
> 
> External Modification Summary:
>   Calls made by other processes targeting this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by all processes on this machine:
>     task_for_pid: 6168
>     thread_create: 0
>     thread_set_state: 0
> 
> VM Region Summary:
> ReadOnly portion of Libraries: Total=464K resident=0K(0%) swapped_out_or_unallocated=464K(100%)
> Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
>  
>                                 VIRTUAL   REGION 
> REGION TYPE                        SIZE    COUNT (non-coalesced) 
> ===========                     =======  ======= 
> STACK GUARD                       56.0M        2 
> Stack                             8192K        2 
> __DATA                             236K        4 
> __LINKEDIT                         132K        3 
> __TEXT                             332K        3 
> shared memory                        8K        3 
> ===========                     =======  ======= 
> TOTAL                             64.7M       11

**Comment by jamesmadelin** [comment]
Hi, sorry for the dupe... I thought I'd checked the other threads! Keep up the great work!

**Comment by egeg53** [comment]
> I just released version 1.1.1.
> Can you confirm it works now?
> 
> Thanks and sorry for the issue!

not working

**Comment by jamesmadelin** [comment]
Thanks, I'll check it!

**Comment by jamesmadelin** [comment]
Hi! V1.1.1 still not working for me with the warning dialogue when I try to open the .app saying "You should move this to the Trash" and no option to do anything else. Clicking the '?' opens Mac Help: "There may be a problem with this app. Although the app was signed by an identified developer, the certificate for the app has been revoked, and it cannot be opened." MbPro 10.13.6
